# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usbhid" "uas" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd" "snd_sof" "snd_sof_pci" "snd_soc_skl" "snd_hda_intel"];
  boot.extraModulePackages = [];

  # Framework-specific audio tweaks
  boot.extraModprobeConfig = ''
    options snd_hda_intel power_save=0
    options snd_hda_intel power_save_controller=N
  '';

  # Framework audio firmware
  hardware.firmware = with pkgs; [
    linux-firmware
    sof-firmware
  ];

  # Ensure PulseAudio is disabled since we're using PipeWire
  services.pulseaudio.enable = false;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/04e42f09-2e97-412a-b3c1-3dad38fd08d9";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/99FE-A587";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/6fa95247-9639-47b2-9493-44a7386610e5";}
  ];

  fileSystems."/run/media/tim/data" = {
    device = "/dev/disk/by-uuid/96da3a24-f2f3-48bc-9a6f-5df5d190b7c3";
    fsType = "ext4";
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp196s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # GPU configuration
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      amdvlk
      rocmPackages.clr
      rocmPackages.clr.icd
    ];
  };

  # Add AMD-specific kernel parameters
  boot.kernelParams = [
    "rtc_cmos.use_acpi_alarm=1" # Workaround for SuspendThenHibernate
    "amdgpu.sg_display=0" # Can help with display stability
  ];

  #hardware services
  services.hardware.bolt.enable = true;
  #hardware.bluetooth.powerOnBoot = true;
  services.blueman.enable = true;

  # Dell docks etc
  services.xserver.videoDrivers = ["modesetting"]; #"displaylink"

  #firmware update service
  services.fwupd.enable = true;

  #finger print scanner service
  services.fprintd.enable = true;

  # AMD has better battery life with PPD over TLP:
  # https://community.frame.work/t/responded-amd-7040-sleep-states/38101/13
  services.power-profiles-daemon.enable = lib.mkDefault true;

  # added services system enviroment for tailscale
  services.tailscale.enable = true;

  environment.etc = {
    "libinput/local-overrides.quirks".text = ''
      [Keyboard]
      MatchUdevType=keyboard
      MatchName=Framework Laptop 16 Keyboard Module - ANSI Keyboard
      AttrKeyboardIntegration=internal
    '';
  };
}
