{pkgs, ...}: {
  environment.systemPackages = with pkgs; [
    audacity
    discord
    nodejs
    obs-studio
    vlc
    teams-for-linux
    firefox
    thunderbird
    lutris
    obs-studio
    gphoto2
    citrix_workspace
    pkgs.yt-dlp
    pkgs.darktable
    pkgs.framework-tool
    pkgs.easyeffects
    neovim
    vscodium-fhs
    pkgs.ryzenadj
    pkgs.element-desktop
    libreoffice-qt
    hunspell
    hunspellDicts.nl_NL
    hunspellDicts.en_US
    amdgpu_top
    pkgs.nextcloud-client
    pkgs.nextcloud-talk-desktop
    xl2tpd
    libfprint
    ollama
    bc
    fmt
    toybox
    pkgs.microsoft-edge
    tailscale-systray
    tailscale
    dive
    gh
    openssh
    openssl
    sshs
    mullvad-vpn
    mullvad
    parted
    dosfstools
    pkgs.signal-desktop
    pkgs.unigine-heaven
    warp-terminal
  ];
}
